name: CI-Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=15.4,name=iPhone 11 Pro Max']
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          xcodebuild clean build -project BluetoothLE.xcodeproj -scheme BluetoothLE -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
