name: CI-Test

on: [push]

jobs:
  test:
    name: Test1
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build and export iOS
        uses: hectorguerrini/build-ios-action@v1.0.4
        with:
          project-path: BluetoothLE.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.DEV_MOBILEPROVISION_BASE64 }}


